#! /usr/bin/env bash

DIRNAME=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

java -jar ~/tool/saxon/saxon-he-12.2.jar "$DIRNAME/../schemas/BPMN20.xsd" "$DIRNAME/codegen-rust.xsl" | rustfmt > "$DIRNAME/src/autogenerated.rs"
