[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
olive_proto = { workspace = true }
rocksdb = "0.21.0"
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
chrono = "0.4.26"